### ISSUE TITLE
ERROR message from the server is not handled

### ISSUE THREAD

**Issue by joeshaw** [fluffle/goirc#92]
I had a client that was calling `client.Connect()` and was receiving `irc.DISCONNECT` events with a line that had no information.  Once I turned on debug logging, I saw:

```
2016/11/17 09:18:04 connection.go:334: INFO irc.Connect(): Connecting to irc.example.com:6697.                                                                    2016/11/17 09:18:04 connection.go:343: INFO irc.Connect(): Performing SSL handshake.                                                                            2016/11/17 09:18:04 connection.go:483: DEBUG -> NICK fooey
2016/11/17 09:18:04 connection.go:418: DEBUG <- :irc.example.com NOTICE * :*** Looking up your hostname...
2016/11/17 09:18:04 connection.go:418: DEBUG <- :irc.example.com NOTICE * :*** Checking Ident                                                                    2016/11/17 09:18:04 connection.go:418: DEBUG <- :irc.example.com NOTICE * :*** Found your hostname
2016/11/17 09:18:04 connection.go:418: DEBUG <- :irc.example.com NOTICE * :*** No Ident response
2016/11/17 09:18:06 connection.go:483: DEBUG -> USER fooey 12 * :fooey
2016/11/17 09:18:06 connection.go:418: DEBUG <- ERROR :Closing Link: example.org (Too many user connections (global))
2016/11/17 09:18:06 connection.go:517: INFO irc.Close(): Disconnected from server.
```

It seems like ERROR responses are fairly well-defined?  It is mentioned in https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#ERROR and in [RFC 1459](https://tools.ietf.org/html/rfc1459#section-4.6.4).

It'd be nice if these were handled by goirc automatically, with the ability for me to override a handler.  (At the very least, it'd be nice if `ERROR` were one of the constants defined for message types.)

**Comment by fluffle** [comment]
Sorry for the lack of response, life is getting in the way. I am reasonably sure that client.ParseLine will handle this case correctly already. The only thing that's missing, as you point out, is an ERROR constant so you're handling that instead of the string "ERROR". Otherwise, *Conn.Handle("ERROR", client.Handler) will DTRT and I think you should be able to take whatever action you want in that handler. Of course, sending messages to the server is probably not going to work out too well ;-)
