### ISSUE TITLE
Conn:String method deadlock

### ISSUE THREAD

**Issue by kitech** [fluffle/goirc#94]
case:

registered the "register" fg event, and then in the event handle call println(c.String()), the deadlock occus.

can use conn.connected var directly in Connected() ?  no lock version.

and i also think, the fghandler will occus more deadlock.

**Comment by fluffle** [comment]
You're completely right, thanks for the bug report. I think the correct thing to do is not hold the lock when the REGISTER event is fired, so that's what I've done. Please re-open this if you find other routes to a deadlock -- I don't have that much time to debug this kind of problem, so I pretty much rely on other people finding them for me :-)
